ARG CUDA_VERSION

FROM nvidia/cuda:${CUDA_VERSION}-cudnn-runtime-ubuntu22.04

ARG PYTHON_VERSION
ARG PROJECT_ID
ARG ETCD_VERSION
ENV GOOGLE_CLOUD_PROJECT=${PROJECT_ID}

RUN apt update && apt install -y \
    # Install build dependencies
    build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev \
    libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev wget liblzma-dev lzma \
    # Install network tools
    curl gnupg telnet net-tools iputils-ping && \
    # Clean up
    apt autoremove && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python from source
RUN wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz && \
    tar -xf Python-${PYTHON_VERSION}.tgz && \
    cd Python-${PYTHON_VERSION} && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make altinstall && \
    cd .. && \
    rm -rf Python-${PYTHON_VERSION} Python-${PYTHON_VERSION}.tgz && \
    update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python${PYTHON_VERSION%.*} 1

# Adapted from https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/training/sdk_pytorch_torchrun_custom_container_training_imagenet.ipynb
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    # Install reduction server plugin on GPU containers. google-fast-socket is
    # previously installed in GPU dlenv containers only and it is not compatible
    # with google-reduction-server.
    if dpkg -s google-fast-socket; then \
    apt remove -y google-fast-socket && \
    apt install -y google-reduction-server; \
    fi

# Install ETCD
RUN mkdir -p /tmp/etcd-download && \
    wget https://storage.googleapis.com/etcd/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-amd64.tar.gz && \
    tar xzvf etcd-${ETCD_VERSION}-linux-amd64.tar.gz -C /tmp/etcd-download --strip-components=1 && \
    rm -f etcd-${ETCD_VERSION}-linux-amd64.tar.gz

# Install pip packages exported from poetry.lock file
COPY images/requirements.txt .
RUN python${PYTHON_VERSION%.*} -m pip install -r requirements.txt

COPY src/utils.py src/utils.py
