ARG CUDA_VERSION

FROM nvidia/cuda:${CUDA_VERSION}-cudnn-runtime-ubuntu22.04

ARG PYTHON_VERSION
ARG PROJECT_ID
ENV GOOGLE_CLOUD_PROJECT=${PROJECT_ID}

# Install build dependencies
RUN apt update && apt install -y \
    build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev \
    libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev wget liblzma-dev lzma \
    && apt autoremove \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python from source
RUN wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
    && tar -xf Python-${PYTHON_VERSION}.tgz \
    && cd Python-${PYTHON_VERSION} \
    && ./configure --enable-optimizations \
    && make -j$(nproc) \
    && make altinstall \
    && cd .. \
    && rm -rf Python-${PYTHON_VERSION} Python-${PYTHON_VERSION}.tgz \
    && update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python${PYTHON_VERSION%.*} 1

# Install pip packages exported from poetry.lock file
COPY images/requirements.txt .
RUN python${PYTHON_VERSION%.*} -m pip install -r requirements.txt